$dir = /home/kukso/.config/hypr/conf
source = $dir/my-programms.conf
source = $dir/autostart.conf
source = $dir/environments.conf
source = $dir/appearance.conf
source = $dir/input.conf
source = $dir/keybinds.conf
source = $dir/windowrules.conf
