input {
    kb_layout = us,ru
    kb_options = grp:caps_toggle

    follow_mouse = 1

    sensitivity = -0.85 # -1.0 - 1.0

    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace
